ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<check_processes() running at /home/hilinetria/PycharmProjects/Test/base/app/settings.py:65> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff5092d3498>()]>>
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:56:40 +0000] "GET / HTTP/1.1" 200 867 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/jquery-3.3.1.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:56:40 +0000] "GET /static/js/jquery-3.3.1.js HTTP/1.1" 200 271971 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/main.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:56:40 +0000] "GET /static/js/main.js HTTP/1.1" 200 2156 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /ws >
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:57:34 +0000] "GET / HTTP/1.1" 200 867 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/jquery-3.3.1.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:57:35 +0000] "GET /static/js/jquery-3.3.1.js HTTP/1.1" 200 271971 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/main.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:57:35 +0000] "GET /static/js/main.js HTTP/1.1" 200 2156 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /ws >
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:05:48 +0000] "GET / HTTP/1.1" 200 867 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:14:57:35 +0000] "GET /ws HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/jquery-3.3.1.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:05:48 +0000] "GET /static/js/jquery-3.3.1.js HTTP/1.1" 200 271971 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/main.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:05:48 +0000] "GET /static/js/main.js HTTP/1.1" 200 2156 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /ws >
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:06:07 +0000] "GET / HTTP/1.1" 200 867 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/jquery-3.3.1.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:06:07 +0000] "GET /static/js/jquery-3.3.1.js HTTP/1.1" 200 271971 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /static/js/main.js >
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:06:07 +0000] "GET /static/js/main.js HTTP/1.1" 200 2156 "http://0.0.0.0:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET /ws >
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
ERROR:aiohttp.web:'value' is undefined
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 346, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/base/app/middlewares.py", line 14, in error_middleware
    response = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 102, in wrapped
    app_key=app_key, encoding=encoding)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 73, in render_template
    text = render_string(template_name, request, context, app_key=app_key)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 64, in render_string
    text = template.render(context)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hilinetria/PycharmProjects/Test/base/app/templates/main.html", line 9, in top-level template code
    <input id="activate" type="checkbox" checked="{{not value.disabled}}">
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'value' is undefined
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:10:42 +0000] "GET / HTTP/1.1" 500 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
ERROR:aiohttp.web:'value' is undefined
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 346, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/base/app/middlewares.py", line 14, in error_middleware
    response = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 102, in wrapped
    app_key=app_key, encoding=encoding)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 73, in render_template
    text = render_string(template_name, request, context, app_key=app_key)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 64, in render_string
    text = template.render(context)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hilinetria/PycharmProjects/Test/base/app/templates/main.html", line 9, in top-level template code
    <input id="activate" type="checkbox" checked="{{not value.disabled}}">
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'value' is undefined
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:10:42 +0000] "GET / HTTP/1.1" 500 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
INFO:aiohttp.web:Request started
INFO:aiohttp.web:<Request GET / >
ERROR:aiohttp.web:'value' is undefined
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/setuptools-39.1.0-py3.6.egg/pkg_resources/__init__.py", line 346, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/base/app/middlewares.py", line 14, in error_middleware
    response = await handler(request)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
    resp = await method()
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 102, in wrapped
    app_key=app_key, encoding=encoding)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 73, in render_template
    text = render_string(template_name, request, context, app_key=app_key)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 64, in render_string
    text = template.render(context)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/hilinetria/PycharmProjects/Test/base/app/templates/main.html", line 9, in top-level template code
    <input id="activate" type="checkbox" checked="{{not value.disabled}}">
  File "/home/hilinetria/PycharmProjects/Test/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'value' is undefined
INFO:aiohttp.access:127.0.0.1 [17/Aug/2018:15:11:22 +0000] "GET / HTTP/1.1" 500 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<check_processes() running at /home/hilinetria/PycharmProjects/Test/base/app/settings.py:66> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9fe0fbda68>()]>>
